routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');


Route::group(['middleware' => ['auth']], function () {

    /** Store Routes */
    Route::resource('stores', 'App\Http\Controllers\StoreController');

    /** Product Routes */
    Route::resource('stores.products', 'App\Http\Controllers\ProductController');

    /** Product Routes */
    Route::resource('products', 'App\Http\Controllers\ProductController');

    /** Category Routes */
    Route::resource('categories', 'App\Http\Controllers\CategoryController');

});

resources/views/partials/footer.blade.php
<!-- Footer -->
<footer class="py-5" id="footer-main">
    <div class="container">
        <div class="row align-items-center justify-content-xl-between">
            <div class="col-xl-6">
                <div class="copyright text-center text-xl-left text-muted">
                    &copy; {{date('Y')}} <a href="{{config('app.url')}}" class="font-weight-bold ml-1" target="_blank">{{config('app.name')}}</a>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/partials/leftColumn.blade.php
<!-- Sidenav -->
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
        <!-- Brand -->
        <div class="sidenav-header  d-flex  align-items-center">
            <a class="navbar-brand" href="{{route('dashboard')}}">
                Fetch App<br> Exercise
            </a>
            <div class=" ml-auto ">
                <!-- Sidenav toggler -->
                <div class="sidenav-toggler d-none d-xl-block" data-action="sidenav-unpin" data-target="#sidenav-main">
                    <div class="sidenav-toggler-inner">
                        <i class="sidenav-toggler-line"></i>
                        <i class="sidenav-toggler-line"></i>
                        <i class="sidenav-toggler-line"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar-inner">
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <!-- Nav items -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{{route('dashboard')}}" class="nav-link">
                            <i class="ni ni-ungroup text-orange"></i>
                            <span class="sidenav-normal"> Dashboard </span>
                        </a>
                    </li>

                    @if(auth()->user()->can('stores-menu-view'))
                        <li class="nav-item">
                            <a class="nav-link" href="#navbar-stores" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-users">
                                <i class="fas fa-boxes text-indigo"></i>
                                <span class="nav-link-text">{{trans('stores.stores_title')}}</span>
                            </a>
                            <div class="collapse" id="navbar-stores">
                                <ul class="nav nav-sm flex-column">
                                    <li class="nav-item">
                                        <a href="{{route('stores.index')}}" class="nav-link">
                                            <span class="sidenav-mini-icon"> S </span>
                                            <span class="sidenav-normal"> {{trans('stores.stores_title')}} </span>
                                        </a>
                                    </li>
                                    @if(auth()->user()->can('stores-create'))
                                        <li class="nav-item">
                                            <a href="{{route('stores.create')}}" class="nav-link">
                                                <span class="sidenav-mini-icon"> CS </span>
                                                <span class="sidenav-normal"> {{trans('stores.create_new')}} </span>
                                            </a>
                                        </li>
                                    @endif
                                </ul>
                            </div>
                        </li>
                    @endif

                    @if(auth()->user()->can('products-index'))
                        <li class="nav-item">
                            <a class="nav-link" href="#navbar-products" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-users">
                                <i class="fas fa-boxes text-indigo"></i>
                                <span class="nav-link-text">{{trans('products.products_title')}}</span>
                            </a>
                            <div class="collapse" id="navbar-products">
                                <ul class="nav nav-sm flex-column">
                                    <li class="nav-item">
                                        <a href="{{route('products.index')}}" class="nav-link">
                                            <span class="sidenav-mini-icon"> P </span>
                                            <span class="sidenav-normal"> {{trans('products.products_title')}} </span>
                                        </a>
                                    </li>
                                    @if(auth()->user()->can('products-create'))
                                        <li class="nav-item">
                                            <a href="{{route('products.create')}}" class="nav-link">
                                                <span class="sidenav-mini-icon"> CP </span>
                                                <span class="sidenav-normal"> {{trans('products.create_new')}} </span>
                                            </a>
                                        </li>
                                    @endif
                                </ul>
                            </div>
                        </li>
                    @endif

                    @if(auth()->user()->can('categories-index'))
                        <li class="nav-item">
                            <a class="nav-link" href="#navbar-product-categories" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-users">
                                <i class="fas fa-network-wired text-indigo"></i>
                                <span class="nav-link-text">{{trans('product-categories.product_categories_title')}}</span>
                            </a>
                            <div class="collapse" id="navbar-product-categories">
                                <ul class="nav nav-sm flex-column">
                                    <li class="nav-item">
                                        <a href="{{route('categories.index')}}" class="nav-link">
                                            <span class="sidenav-mini-icon"> U </span>
                                            <span class="sidenav-normal"> {{trans('product-categories.product_categories_title')}} </span>
                                        </a>
                                    </li>
                                    @if(auth()->user()->can('categories-create'))
                                        <li class="nav-item">
                                            <a href="{{route('categories.create')}}" class="nav-link">
                                                <span class="sidenav-mini-icon"> CU </span>
                                                <span class="sidenav-normal"> {{trans('product-categories.create_new')}} </span>
                                            </a>
                                        </li>
                                    @endif
                                </ul>
                            </div>
                        </li>
                    @endif

                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/partials/topMenu.blade.php
<!-- Topnav -->
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Navbar links -->
            <ul class="navbar-nav align-items-center  ml-md-auto ">
                <li class="nav-item d-xl-none">
                    <!-- Sidenav toggler -->
                    <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </div>
                </li>
                <li class="nav-item d-sm-none">
                    <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                        <i class="ni ni-zoom-split-in"></i>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="ni ni-bell-55"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden">
                        <!-- Dropdown header -->
                        <div class="px-3 py-3">
                            <h6 class="text-sm text-muted m-0">You have <strong class="text-primary">0</strong> notifications.</h6>
                        </div>
                        <!-- List group -->
                        <div class="list-group list-group-flush">

                        </div>
                        <!-- View all -->
                        <a href="#!" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>
                    </div>
                </li>

            </ul>
            <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
                <li class="nav-item dropdown">
                    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="media align-items-center">
                            <span class="avatar avatar-sm rounded-circle">
                                <img alt="Image placeholder" src="../../assets/img/theme/team-5.jpg">
                            </span>
                            <div class="media-body  ml-2  d-none d-lg-block">
                                <span class="mb-0 text-sm  font-weight-bold">{{Auth::user()->name}}</span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu  dropdown-menu-right ">
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome!</h6>
                        </div>
                        <div class="dropdown-divider"></div>
                        <a href="{{ route('logout') }}"
                           class="dropdown-item"
                           onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                            <span>{{ __('Logout') }}</span>
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>