routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');


Route::group(['middleware' => ['auth']], function () {

    /** Store Routes */
    Route::resource('stores', 'App\Http\Controllers\StoreController');

    /** Product Routes */
    Route::resource('stores.products', 'App\Http\Controllers\ProductController');

    /** Product Routes */
    Route::resource('products', 'App\Http\Controllers\ProductController');

    /** Category Routes */
    Route::resource('categories', 'App\Http\Controllers\CategoryController');

});

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\ProductCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {

        $productCategories = ProductCategory::all();

        return view('layouts.categories.index')->with([
            'data' => $productCategories
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|View
     */
    public function create()
    {
        return view('layouts.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {

        $newCategory = null;

        $messages = [
            'category_name.required' => "Category name is required",
            'category_name.regex' => "Category name is not valid",
            'category_name.unique' => "Category name is exists",
        ];

        $rules = [
            'category_name'      =>  'required|max:255|string|regex:/^[\pL\s\-]+$/u',
        ];

        $validator = Validator::make($request->all(),$rules,$messages);

        if ($validator->fails()){

            return response()->json([
                'errors'    =>  $validator->getMessageBag()
            ]);

        } else {

            DB::beginTransaction();

            try {

                $newCategory = ProductCategory::create([
                    'name'                  => $validator->valid()['category_name'],
                ]);

            } catch (\Exception $e){

                Log::error($e->getMessage());

                DB::rollBack();

            }

            DB::commit();

        }

        return response()->json(['url' => route('categories.show',['category' => $newCategory->id])]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show($id)
    {

        $data = ProductCategory::find($id);

        return view('layouts.categories.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = ProductCategory::find($id);

        return view('layouts.categories.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     */
    public function update(Request $request, int $id)
    {

        $messages = [
            'category_name.required' => "Category name is required",
            'category_name.regex' => "Category name is not valid",
            'category_name.unique' => "Category name is exists",
        ];

        $rules = [
            'category_name'      =>  'required|max:255|string|regex:/^[\pL\s\-]+$/u',
        ];

        $validator = Validator::make($request->all(),$rules,$messages);

        if ($validator->fails()){

            return response()->json([
                'errors'    =>  $validator->getMessageBag()
            ]);

        } else {

            DB::beginTransaction();

            try {

                ProductCategory::where('id', $id)->update([
                    'name'                  => $validator->valid()['category_name'],
                ]);

            } catch (\Exception $e){

                Log::error($e->getMessage());

                DB::rollBack();

            }

            DB::commit();

            $productCategory = ProductCategory::find($id);

        }

        return response()->json(['url' => route('categories.show',['category' => $productCategory->id])]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/categories/create.blade.php
@extends('layouts.app')

@section('header')
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">{{trans('product-categories.create_new')}}</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                @can('dashboard_view')
                                    <li class="breadcrumb-item"><a href="{{ route('home') }}"><i class="fas fa-home"></i></a></li>
                                @endcan
                                @can('categories-index')
                                    <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">{{trans('product-categories.product_categories_title')}}</a></li>
                                @endcan
                                @can('categories-create')
                                    <li class="breadcrumb-item active" aria-current="page">{{trans('product-categories.create_new')}}</li>
                                @endcan
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">
                        @can('categories-index')
                            <a href="{{ route('categories.index') }}" class="btn btn-sm btn-neutral">Back</a>
                        @endcan
                            @can('categories-create')
                            <button type="submit" id="form-submit" form="category_create_form" class="btn btn-sm btn-neutral">{{ trans('product-categories.create_btn') }}</button>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card card-frame">
                <div class="card-body">

                    <form id="category_create_form" action="{{ route('categories.store') }}" method="POST">

                        @csrf

                        {{-- Text Input --}}
                        <div class="form-group col-12 col-md-6">

                            {{-- Input Label --}}
                            <label id="category_name_label" class="form-control-label" for="category_name">Category Name</label>

                            {{-- Input --}}
                            <input type="text" class="form-control" name="category_name" id="category_name" placeholder="e.g. Shoes" aria-describedby="category_name_help">

                            {{-- Help Message --}}
                            <small id="category_name_help" class="form-text text-muted">Please add category name</small>

                            {{-- Validation Failed --}}
                            <div id="invalid_category_name" class="invalid-feedback"></div>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('footer_scripts')

    <script src="{{asset('/assets/vendor/select2/dist/js/select2.min.js')}}"></script>

    <script>

        /** Form variable */
        let form = $("#category_create_form");

        /** Handle form submit on click */
        $('#form-submit').on('click', function (e){

            //Prevent form submission
            e.preventDefault();

            //Post form with AJAX
            postForm();
        });


        function postForm(){

            $.ajax({
                url: '{{route('categories.store')}}',
                type:'POST',
                data:form.serialize(),
                beforeSend:function (){
                    $('.invalid-feedback').html('');
                },
                success:function(response){

                    if (response.errors){

                        /** Loop errors */
                        $.each(response.errors, function (errorIndex, error){

                            /** Add invalid class to input element */
                            $('#'+errorIndex).addClass('invalid');

                            /** Loop error messages */
                            $.each(error, function (messageIndex, error){
                                $('#invalid_'+errorIndex).addClass('show').append('<span class="error-message">'+error+'</span>')
                            });

                        })
                    } else if (response.url){
                        window.location=response.url;
                    }
                },
            });

        }

    </script>

@endsection

resources/views/layouts/categories/edit.blade.php
@extends('layouts.app')

@section('header')
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">{{trans('product-categories.create_new')}}</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                @can('dashboard_view')
                                    <li class="breadcrumb-item"><a href="{{ route('home') }}"><i class="fas fa-home"></i></a></li>
                                @endcan
                                @can('categories-index')
                                    <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">{{trans('product-categories.product_categories_title')}}</a></li>
                                @endcan
                                @can('categories-edit')
                                    <li class="breadcrumb-item active" aria-current="page">{{trans('product-categories.save')}}</li>
                                @endcan
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">
                        @can('categories-index')
                            <a href="{{ route('categories.index') }}" class="btn btn-sm btn-neutral">Back</a>
                        @endcan
                            @can('categories-edit')
                            <button type="submit" id="form-submit" form="category_edit_form" class="btn btn-sm btn-neutral">{{ trans('product-categories.save_btn') }}</button>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card card-frame">
                <div class="card-body">

                    <form id="category_edit_form" action="{{route('categories.update',['category' => $data->id])}}" method="put">

                        @csrf

                        {{-- Text Input --}}
                        <div class="form-group col-12 col-md-6">

                            {{-- Input Label --}}
                            <label id="category_name_label" class="form-control-label" for="category_name">Category Name</label>

                            {{-- Input --}}
                            <input type="text" class="form-control" name="category_name" id="category_name" placeholder="e.g. Shoes" aria-describedby="category_name_help" value="{{$data->name}}">

                            {{-- Help Message --}}
                            <small id="category_name_help" class="form-text text-muted">Please add category name</small>

                            {{-- Validation Failed --}}
                            <div id="invalid_category_name" class="invalid-feedback"></div>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('footer_scripts')

    <script src="{{asset('/assets/vendor/select2/dist/js/select2.min.js')}}"></script>

    <script>

        /** Form variable */
        let form = $("#category_edit_form");

        /** Handle form submit on click */
        $('#form-submit').on('click', function (e){

            //Prevent form submission
            e.preventDefault();

            console.log('asdfasdfasdfasdfasdf')

            //Post form with AJAX
            postForm();
        });


        function postForm(){

            $.ajax({
                url: '{{route('categories.update',['category' => $data->id])}}',
                type:'patch',
                data:form.serialize(),
                beforeSend:function (){
                    $('.invalid-feedback').html('');
                },
                success:function(response){

                    if (response.errors){

                        /** Loop errors */
                        $.each(response.errors, function (errorIndex, error){

                            /** Add invalid class to input element */
                            $('#'+errorIndex).addClass('invalid');

                            /** Loop error messages */
                            $.each(error, function (messageIndex, error){
                                $('#invalid_'+errorIndex).addClass('show').append('<span class="error-message">'+error+'</span>')
                            });

                        })
                    } else if (response.url){
                        window.location=response.url;
                    }
                },
            });

        }

    </script>

@endsection

resources/views/layouts/categories/index.blade.php
@extends('layouts.app')

@push('extra-styles')

    <link href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" rel="stylesheet">

@endpush

@section('header')
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">{{trans('product-categories.product_categories_title')}}</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                @can('dashboard_view')
                                    <li class="breadcrumb-item"><a href="{{ route('home') }}"><i class="fas fa-home"></i></a></li>
                                @endcan
                                @can('categories-index')
                                    <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">{{trans('product-categories.product_categories_title')}}</a></li>
                                @endcan
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">
                        @can('categories-index')
                            <a href="{{ route('categories.index') }}" class="btn btn-sm btn-neutral">Back</a>
                        @endcan
                        @can('categories-create')
                            <a href="{{route('categories.create')}}" class="btn btn-sm btn-neutral">{{ trans('product-categories.create_btn') }}</a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-frame">
                <div class="card-body">
                    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <div>
                        <table id="table-products" class="table align-items-center">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col" class="sort" data-sort="id">ID</th>
                                    <th scope="col" class="sort" data-sort="name">Name</th>
                                    <th scope="col" class="sort" data-sort="products">Products</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody class="list">

                            @foreach($data as $category)

                                <tr>
                                    <th scope="row">
                                        {{$category->id}}
                                    </th>

                                    <td class="name">
                                        {{$category->name}}
                                    </td>

                                    <td class="products">
                                        {{$category->name}}
                                    </td>

                                    <td class="text-right">
                                        <div class="dropdown">
                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                <a class="dropdown-item" href="{{ route('categories.show',['category' => $category->id]) }}">View</a>
                                                <a class="dropdown-item" href="{{ route('categories.edit',['category' => $category->id]) }}">Edit</a>
                                            </div>
                                        </div>
                                    </td>

                                </tr>

                            @endforeach

                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('extra-scripts')

    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>

    <script>

        $(document).ready( function () {
            $('#table-products').DataTable();
        } );
    </script>

@endpush

resources/views/layouts/categories/show.blade.php
@extends('layouts.app')

@section('header')

    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">{{trans('product-categories.product_category_title')}}</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                @can('dashboard_view')
                                    <li class="breadcrumb-item"><a href="{{ route('home') }}"><i class="fas fa-home"></i></a></li>
                                @endcan
                                @can('categories-index')
                                    <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">{{trans('product-categories.product_categories_title')}}</a></li>
                                @endcan
                                @can('categories-create')
                                    <li class="breadcrumb-item active" aria-current="page">{{trans('product-categories.view')}}</li>
                                @endcan
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">
                        @can('categories-index')
                            <a href="{{ route('categories.index') }}" class="btn btn-sm btn-neutral">Back</a>
                        @endcan
                        @can('categories-create')
                                <a href="{{ route('categories.edit',['category' => $data->id]) }}" class="btn btn-sm btn-neutral">Edit</a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')

    <div class="card mb-4">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label class="form-control-label">Category Name: </label>
                        <span class="d-block">{!! $data->name !!}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection