routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');


Route::group(['middleware' => ['auth']], function () {

    /** Store Routes */
    Route::resource('stores', 'App\Http\Controllers\StoreController');

    /** Product Routes */
    Route::resource('stores.products', 'App\Http\Controllers\ProductController');

    /** Product Routes */
    Route::resource('products', 'App\Http\Controllers\ProductController');

    /** Category Routes */
    Route::resource('categories', 'App\Http\Controllers\CategoryController');

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Product extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'price', 'category_id'
    ];

    /**
     * Get the category associated with the product.
     *
     */
    public function category()
    {
        return $this->hasOneThrough(
            ProductCategory::class,
            MapProductCategory::class,
            'product_id', // Foreign key on the cars table...
            'id', // Foreign key on the owners table...
            'id', // Local key on the mechanics table...
            'category_id' // Local key on the cars table...
            );
    }

    /**
     * Get the category associated with the product.
     *
     */
    public function store()
    {
        return $this->hasOneThrough(
            Store::class,
            MapStoreProducts::class,
            'product_id',
            'id',
            'id',
            'store_id'
        );
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\MapProductCategory;
use App\Models\MapStoreProducts;
use App\Models\MapUserStore;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\Store;
use App\Models\StoreProducts;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {

        if ( Auth::user()->hasRole('super-admin')) {

            $products = Product::with('category', 'store')->get();

            $data = (object) [
                'products' => $products
            ];

            return view('layouts.products.index')->with([
                'data' => $data
            ]);
        }

        $data = User::where('id','=', Auth::id())->with('stores', 'stores.products', 'stores.products.category')->first();

        return view('layouts.products.index')->with([
            'data' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {

        $productCategories = ProductCategory::all();

        $user = User::with('stores')->find(Auth::id());

        return view('layouts.products.create')->with([
            'data' => $productCategories,
            'stores' => $user->stores,
        ]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {

        $newProduct = null;

        $messages = [
            'product_name.required' => "Product name is required",
            'product_price.required' => "Product price is required",
        ];

        $rules = [
            'product_name' => 'required|max:255|string',
            'product_price' => 'required',
        ];

        $validator = Validator::make($request->all(),$rules,$messages);


        if ($validator->fails()){

            return response()->json([
                'errors'    =>  $validator->getMessageBag()
            ]);

        } else {

            DB::beginTransaction();

            try {

                $newProduct = Product::create([
                    'name'                  => $validator->valid()['product_name'],
                    'price'                 => $validator->valid()['product_price'],
                ]);

                MapStoreProducts::create([
                    'product_id'      =>   $newProduct->id,
                    'store_id'    =>   $validator->valid()['store_id'],
                ]);

                MapProductCategory::create([
                    'product_id'     =>   $newProduct->id,
                    'category_id'    =>   $validator->valid()['product_category_id']
                ]);

            } catch (\Exception $e){

                Log::error($e->getMessage());

                DB::rollBack();

            }

            DB::commit();


            return response()->json(['url' => route('products.show',['product' => $newProduct->id])]);

        }




    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Product::with('category','store')->find($id);

        return view('layouts.products.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::with('category', 'store')->find($id);

        $productCategories = ProductCategory::all();

        $user = User::with('stores')->find(Auth::id());

        return view('layouts.products.edit')->with([
            'product' => $product,
            'data' => $productCategories,
            'stores' => $user->stores,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\JsonResponse
     */
    public function update(Request $request, $id)
    {

        $messages = [
            'product_name.required' => "Product name is required",
            'product_price.required' => "Product price is required",
        ];

        $rules = [
            'product_name' => 'required|max:255|string',
            'product_price' => 'required',
        ];

        $validator = Validator::make($request->all(),$rules,$messages);

        if ($validator->fails()){

            return response()->json([
                'errors'    =>  $validator->getMessageBag()
            ]);

        } else {

            DB::beginTransaction();

            try {

                Product::where('id', $id)->update([
                    'name'                  => $validator->valid()['product_name'],
                    'price'                 => $validator->valid()['product_price'],
                ]);

                MapStoreProducts::where('product_id','=', $id)->update([
                    'store_id'    =>   $validator->valid()['store_id'],
                ]);

                MapProductCategory::where('product_id','=', $id)->update([
                    'category_id'    =>   $validator->valid()['product_category_id']
                ]);

            } catch (\Exception $e){

                Log::error($e->getMessage());

                DB::rollBack();

            }

            DB::commit();

            $product = Product::find($id);

        }

        return response()->json(['url' => route('products.show',['product' => $product->id])]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/products/create.blade.php
@extends('layouts.app')

@section('header')
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">{{trans('products.create_new')}}</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                @can('dashboard_view')
                                    <li class="breadcrumb-item"><a href="{{ route('home') }}"><i class="fas fa-home"></i></a></li>
                                @endcan
                                @can('products-index')
                                    <li class="breadcrumb-item"><a href="{{ route('products.index') }}">{{trans('products.products_title')}}</a></li>
                                @endcan
                                @can('products-create')
                                    <li class="breadcrumb-item active" aria-current="page">{{trans('products.create_new')}}</li>
                                @endcan
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">
                        @can('products-index')
                            <a href="{{ route('products.index') }}" class="btn btn-sm btn-neutral">Back</a>
                        @endcan
                            @can('products-create')
                            <button type="submit" id="form-submit" form="product_create_form" class="btn btn-sm btn-neutral">{{ trans('products.create_btn') }}</button>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card card-frame">
                <div class="card-body">

                    <form id="product_create_form" action="{{ route('products.store') }}" method="POST">

                        @csrf

                        <div class="form-row">

                            {{-- Text Input --}}
                            <div class="form-group col-12 col-md-4">

                                {{-- Input Label --}}
                                <label id="product_name_label" class="form-control-label" for="product_name">Product Name</label>

                                {{-- Input --}}
                                <input type="text" class="form-control" name="product_name" id="product_name" placeholder="e.g. Shoes" aria-describedby="product_name_help">

                                {{-- Help Message --}}
                                <small id="product_name_help" class="form-text text-muted">Please add product name</small>

                                {{-- Validation Failed --}}
                                <div id="invalid_product_name" class="invalid-feedback"></div>

                            </div>

                            {{-- Number Input --}}
                            <div class="form-group col-12 col-md-4">

                                {{-- Input Label --}}
                                <label id="product_price_label" class="form-control-label" for="product_price">Product Price</label>

                                {{-- Input --}}
                                <input type="number" min="0" class="form-control" name="product_price" id="product_price" aria-describedby="product_price_help">

                                {{-- Help Message --}}
                                <small id="product_price_help" class="form-text text-muted">Please add product price</small>

                                {{-- Validation Failed --}}
                                <div id="invalid_product_price" class="invalid-feedback"></div>

                            </div>


                            {{-- Select Input --}}
                            <div class="form-group col-12 col-md-4">

                                {{-- Input Label --}}
                                <label for="product_category_id" class="form-control-label">Product Category</label>

                                {{-- Input --}}
                                <select
                                        class="form-control select2"
                                        aria-describedby="product_category_help"
                                        name="product_category_id"
                                        id="product_category_id"
                                        data-toggle="select"
                                >
                                    <option value="-1">Select</option>
                                    @if(isset($data))
                                        @foreach($data as $key => $productCategory)
                                            <option value="{{$productCategory->id}}">{{$productCategory->name}}</option>
                                        @endforeach
                                    @endif

                                </select>

                                {{-- Help Message --}}
                                <small id="product_category_id_help" class="form-text text-muted">Select product category</small>

                                {{-- Validation Failed --}}
                                <div id="invalid-product_category_id" class="invalid-feedback"></div>

                            </div>

                            {{-- Select Input --}}
                            <div class="form-group col-12 col-md-4">

                                {{-- Input Label --}}
                                <label for="product_store_id" class="form-control-label">Store</label>

                                {{-- Input --}}
                                <select
                                        class="form-control select2"
                                        aria-describedby="store_help"
                                        name="store_id"
                                        id="store_id"
                                        data-toggle="select"
                                >
                                    <option value="-1">Select</option>
                                    @if(isset($stores))
                                        @foreach($stores as $key => $store)
                                            <option value="{{$store->id}}">{{$store->name}}</option>
                                        @endforeach
                                    @endif

                                </select>

                                {{-- Help Message --}}
                                <small id="store_id_help" class="form-text text-muted">Select Store</small>

                                {{-- Validation Failed --}}
                                <div id="invalid-store_id" class="invalid-feedback"></div>

                            </div>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('footer_scripts')

    <script>

        /** Form variable */
        let form = $("#product_create_form");

        /** Handle form submit on click */
        $('#form-submit').on('click', function (e){

            //Prevent form submission
            e.preventDefault();

            //Post form with AJAX
            postForm();

        });


        function postForm(){

            $.ajax({
                url: '{{route('products.store')}}',
                type:'POST',
                data:form.serialize(),
                beforeSend:function (){
                    $('.invalid-feedback').html('');
                },
                success:function(response){

                    if (response.errors){

                        /** Loop errors */
                        $.each(response.errors, function (errorIndex, error){

                            /** Add invalid class to input element */
                            $('#'+errorIndex).addClass('invalid');

                            /** Loop error messages */
                            $.each(error, function (messageIndex, error){
                                $('#invalid_'+errorIndex).addClass('show').append('<span class="error-message">'+error+'</span>')
                            });

                        })
                    } else if (response.url){
                        window.location=response.url;
                    }
                },
            });

        }

    </script>

@endsection

resources/views/layouts/products/edit.blade.php
@extends('layouts.app')

@section('header')
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">{{trans('products.create_new')}}</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                @can('dashboard_view')
                                    <li class="breadcrumb-item"><a href="{{ route('home') }}"><i class="fas fa-home"></i></a></li>
                                @endcan
                                @can('products-index')
                                    <li class="breadcrumb-item"><a href="{{ route('products.index') }}">{{trans('products.products_title')}}</a></li>
                                @endcan
                                @can('products-edit')
                                    <li class="breadcrumb-item active" aria-current="page">{{trans('products.save')}}</li>
                                @endcan
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">
                        @can('products-index')
                            <a href="{{ route('products.index') }}" class="btn btn-sm btn-neutral">Back</a>
                        @endcan
                            @can('products-edit')
                            <button type="submit" id="form-submit" form="product_edit_form" class="btn btn-sm btn-neutral">{{ trans('products.save_btn') }}</button>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card card-frame">
                <div class="card-body">

                    <form id="product_edit_form" action="{{route('products.update',['product' => $product->id])}}" method="put">

                        @csrf

                        {{-- Text Input --}}
                        <div class="form-group col-12 col-md-4">

                            {{-- Input Label --}}
                            <label id="product_name_label" class="form-control-label" for="product_name">Product Name</label>

                            {{-- Input --}}
                            <input type="text" class="form-control" name="product_name" id="product_name" placeholder="e.g. Shoes" aria-describedby="product_name_help"  value="{{$product->name}}">

                            {{-- Help Message --}}
                            <small id="product_name_help" class="form-text text-muted">Please add product name</small>

                            {{-- Validation Failed --}}
                            <div id="invalid_product_name" class="invalid-feedback"></div>

                        </div>

                        {{-- Number Input --}}
                        <div class="form-group col-12 col-md-4">

                            {{-- Input Label --}}
                            <label id="product_price_label" class="form-control-label" for="product_price">Product Price</label>

                            {{-- Input --}}
                            <input type="number" min="0" step=".01" class="form-control" name="product_price" id="product_price" aria-describedby="product_price_help" value="{{$product->price}}">

                            {{-- Help Message --}}
                            <small id="product_price_help" class="form-text text-muted">Please add product price</small>

                            {{-- Validation Failed --}}
                            <div id="invalid_product_price" class="invalid-feedback"></div>

                        </div>


                        {{-- Select Input --}}
                        <div class="form-group col-12 col-md-4">

                            {{-- Input Label --}}
                            <label for="product_category" class="form-control-label">Product Category</label>

                            {{-- Input --}}
                            <select
                                    class="form-control select2"
                                    aria-describedby="product_category_help"
                                    name="product_category_id"
                                    id="product_category"
                                    data-toggle="select"
                            >
                                <option value="-1">Select</option>
                                @if(isset($data))
                                    @foreach($data as $key => $productCategory)
                                        <option value="{{$productCategory->id}}"
                                                @if ($product->category->id == $productCategory->id) {{'selected'}} @endif
                                        >{{$productCategory->name}}</option>
                                    @endforeach
                                @endif

                            </select>

                            {{-- Help Message --}}
                            <small id="product_category_help" class="form-text text-muted">Select product category</small>

                            {{-- Validation Failed --}}
                            <div id="invalid-product_category" class="invalid-feedback"></div>

                        </div>

                        {{-- Select Input --}}
                        <div class="form-group col-12 col-md-4">

                            {{-- Input Label --}}
                            <label for="product_store_id" class="form-control-label">Store</label>

                            {{-- Input --}}
                            <select
                                    class="form-control select2"
                                    aria-describedby="store_help"
                                    name="store_id"
                                    id="store_id"
                                    data-toggle="select"
                            >
                                <option value="-1">Select</option>
                                @if(isset($stores))
                                    @foreach($stores as $key => $store)
                                        <option value="{{$store->id}}"
                                        @if ($product->store->id == $store->id) {{'selected'}} @endif
                                        >{{$store->name}}</option>
                                    @endforeach
                                @endif

                            </select>

                            {{-- Help Message --}}
                            <small id="store_id_help" class="form-text text-muted">Select Store</small>

                            {{-- Validation Failed --}}
                            <div id="invalid-store_id" class="invalid-feedback"></div>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('footer_scripts')

    <script src="{{asset('/assets/vendor/select2/dist/js/select2.min.js')}}"></script>

    <script>

        /** Form variable */
        let form = $("#product_edit_form");

        /** Handle form submit on click */
        $('#form-submit').on('click', function (e){

            //Prevent form submission
            e.preventDefault();

            //Post form with AJAX
            postForm();
        });


        function postForm(){

            $.ajax({
                url: '{{route('products.update',['product' => $product->id])}}',
                type:'patch',
                data:form.serialize(),
                beforeSend:function (){
                    $('.invalid-feedback').html('');
                },
                success:function(response){

                    if (response.errors){

                        /** Loop errors */
                        $.each(response.errors, function (errorIndex, error){

                            /** Add invalid class to input element */
                            $('#'+errorIndex).addClass('invalid');

                            /** Loop error messages */
                            $.each(error, function (messageIndex, error){
                                $('#invalid_'+errorIndex).addClass('show').append('<span class="error-message">'+error+'</span>')
                            });

                        })
                    } else if (response.url){
                        window.location=response.url;
                    }
                },
            });

        }

    </script>

@endsection

resources/views/layouts/products/show.blade.php
@extends('layouts.app')

@section('header')

    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">{{trans('products.products_title')}}</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                @can('dashboard_view')
                                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="fas fa-home"></i></a></li>
                                @endcan
                                @can('products-index')
                                    <li class="breadcrumb-item"><a href="{{ route('products.index') }}">{{trans('products.products_title')}}</a></li>
                                @endcan
                                @can('products-create')
                                    <li class="breadcrumb-item active" aria-current="page">{{trans('products.view')}}</li>
                                @endcan
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">
                        @can('products-index')
                            <a href="{{ route('products.index') }}" class="btn btn-sm btn-neutral">Back</a>
                        @endcan
                        @can('products-create')
                                <a href="{{ route('products.edit',['product' => $data->id]) }}" class="btn btn-sm btn-neutral">Edit</a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')

    <div class="card mb-4">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    @if(isset($data->name))
                        <div class="form-group">
                            <label class="form-control-label">Product Name: </label>
                            <span class="d-block">{!! $data->name !!}</span>
                        </div>
                    @endif
                    @if(isset($data->price))
                        <div class="form-group">
                            <label class="form-control-label">Product Price: </label>
                            <span class="d-block">&euro;{!! number_format($data->price, 2) !!}</span>
                        </div>
                    @endif
                    @if(isset($data->category))
                        <div class="form-group">
                            <label class="form-control-label">Category Name: </label>
                            <span class="d-block">{!! $data->category->name !!}</span>
                        </div>
                    @endif
                    @if(isset($data->store))
                        <div class="form-group">
                            <label class="form-control-label">Store Name: </label>
                            <span class="d-block">{!! $data->store->name !!}</span>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

@endsection