routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');


Route::group(['middleware' => ['auth']], function () {

    /** Store Routes */
    Route::resource('stores', 'App\Http\Controllers\StoreController');

    /** Product Routes */
    Route::resource('stores.products', 'App\Http\Controllers\ProductController');

    /** Product Routes */
    Route::resource('products', 'App\Http\Controllers\ProductController');

    /** Category Routes */
    Route::resource('categories', 'App\Http\Controllers\CategoryController');

});

app/Models/Store.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
    ];

    /**
     * Get the products associated with the store.
     *
     */
    public function products()
    {
        return $this->hasManyThrough(
            Product::class,
            MapStoreProducts::class,
            'store_id',
            'id',
            'id',
            'product_id'
        );
    }

}

app/Http/Controllers/StoreController.php
<?php

namespace App\Http\Controllers;

use App\Models\MapProductCategory;
use App\Models\MapStoreProducts;
use App\Models\MapUserStore;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\Store;
use App\Models\StoreProducts;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;

class StoreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        if ( Auth::user()->hasRole('super-admin')) {

            $stores = Store::with('products')->get();

            $data = (object) [
                'stores' => $stores
            ];

            return view('layouts.stores.index')->with([
                'data' => $data
            ]);
        }

        $data = User::where('id','=', Auth::id())->with('stores', 'stores.products')->first();

        return view('layouts.stores.index')->with([
            'data' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        return view('layouts.stores.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(Request $request)
    {
        $newStore = null;

        $messages = [
            'store_name.required' => "Store name is required",
        ];

        $rules = [
            'store_name' => 'required|max:255|string',
        ];

        $validator = Validator::make($request->all(),$rules,$messages);


        if ($validator->fails()){

            return response()->json([
                'errors'    =>  $validator->getMessageBag()
            ]);

        } else {

            DB::beginTransaction();

            try {

                $newStore = Store::create([
                    'name'                  => $validator->valid()['store_name'],
                ]);

                MapUserStore::create([
                    'user_id'      =>   Auth::id(),
                    'store_id'    =>   $newStore->id,
                ]);

            } catch (\Exception $e){

                Log::error($e->getMessage());

                DB::rollBack();

            }

            DB::commit();

            return response()->json(['url' => route('stores.show',['store' => $newStore->id])]);

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     */
    public function show($id)
    {
        $data = Store::find($id);

        return view('layouts.stores.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function edit($id)
    {
        $store = Store::find($id);


        return view('layouts.stores.edit')->with([
            'store' => $store,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\JsonResponse
     */
    public function update(Request $request, $id)
    {
        $messages = [
            'store_name.required' => "Store name is required",
        ];

        $rules = [
            'store_name' => 'required|max:255|string',
        ];

        $validator = Validator::make($request->all(),$rules,$messages);

        if ($validator->fails()){

            return response()->json([
                'errors'    =>  $validator->getMessageBag()
            ]);

        } else {

            DB::beginTransaction();

            try {

                Store::where('id', $id)->update([
                    'name'                  => $validator->valid()['store_name'],
                ]);

            } catch (\Exception $e){

                Log::error($e->getMessage());

                DB::rollBack();

            }

            DB::commit();

            $store = Store::find($id);

        }

        return response()->json(['url' => route('stores.show',['store' => $store->id])]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/stores/create.blade.php
@extends('layouts.app')

@section('header')
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">{{trans('stores.create_new')}}</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                @can('dashboard_view')
                                    <li class="breadcrumb-item"><a href="{{ route('home') }}"><i class="fas fa-home"></i></a></li>
                                @endcan
                                @can('stores-index')
                                    <li class="breadcrumb-item"><a href="{{ route('stores.index') }}">{{trans('stores.stores_title')}}</a></li>
                                @endcan
                                @can('stores-create')
                                    <li class="breadcrumb-item active" aria-current="page">{{trans('stores.create_new')}}</li>
                                @endcan
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">
                        @can('stores-index')
                            <a href="{{ route('stores.index') }}" class="btn btn-sm btn-neutral">Back</a>
                        @endcan
                            @can('stores-create')
                            <button type="submit" id="form-submit" form="product_create_form" class="btn btn-sm btn-neutral">{{ trans('stores.create_btn') }}</button>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card card-frame">
                <div class="card-body">

                    <form id="store_create_form" action="{{ route('stores.store') }}" method="POST">

                        @csrf

                        <div class="form-row">

                            {{-- Text Input --}}
                            <div class="form-group col-12 col-md-4">

                                {{-- Input Label --}}
                                <label id="store_name_label" class="form-control-label" for="store_name">Store Name</label>

                                {{-- Input --}}
                                <input type="text" class="form-control" name="store_name" id="store_name" placeholder="e.g. ShoeBox" aria-describedby="store_name_help">

                                {{-- Help Message --}}
                                <small id="store_name_help" class="form-text text-muted">Please add store name</small>

                                {{-- Validation Failed --}}
                                <div id="invalid_store_name" class="invalid-feedback"></div>

                            </div>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('footer_scripts')

    <script>

        /** Form variable */
        let form = $("#store_create_form");

        /** Handle form submit on click */
        $('#form-submit').on('click', function (e){

            //Prevent form submission
            e.preventDefault();

            //Post form with AJAX
            postForm();

        });


        function postForm(){

            $.ajax({
                url: '{{route('stores.store')}}',
                type:'POST',
                data:form.serialize(),
                beforeSend:function (){
                    $('.invalid-feedback').html('');
                },
                success:function(response){

                    if (response.errors){

                        /** Loop errors */
                        $.each(response.errors, function (errorIndex, error){

                            /** Add invalid class to input element */
                            $('#'+errorIndex).addClass('invalid');

                            /** Loop error messages */
                            $.each(error, function (messageIndex, error){
                                $('#invalid_'+errorIndex).addClass('show').append('<span class="error-message">'+error+'</span>')
                            });

                        })
                    } else if (response.url){
                        window.location=response.url;
                    }
                },
            });

        }

    </script>

@endsection

resources/views/layouts/stores/edit.blade.php
@extends('layouts.app')

@section('header')
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">{{trans('stores.create_new')}}</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                @can('dashboard_view')
                                    <li class="breadcrumb-item"><a href="{{ route('home') }}"><i class="fas fa-home"></i></a></li>
                                @endcan
                                @can('stores-index')
                                    <li class="breadcrumb-item"><a href="{{ route('stores.index') }}">{{trans('stores.stores_title')}}</a></li>
                                @endcan
                                @can('stores-edit')
                                    <li class="breadcrumb-item active" aria-current="page">{{trans('stores.save')}}</li>
                                @endcan
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">
                        @can('stores-index')
                            <a href="{{ route('stores.index') }}" class="btn btn-sm btn-neutral">Back</a>
                        @endcan
                            @can('stores-edit')
                            <button type="submit" id="form-submit" form="product_edit_form" class="btn btn-sm btn-neutral">{{ trans('stores.save_btn') }}</button>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card card-frame">
                <div class="card-body">

                    <form id="store_edit_form" action="{{route('stores.update',['store' => $store->id])}}" method="put">

                        @csrf

                        {{-- Text Input --}}
                        <div class="form-group col-12 col-md-4">

                            {{-- Input Label --}}
                            <label id="store_name_label" class="form-control-label" for="store_name">Store Name</label>

                            {{-- Input --}}
                            <input type="text" class="form-control" name="store_name" id="store_name" placeholder="e.g. ShoeBox" aria-describedby="store_name_help" value="{{$store->name}}">

                            {{-- Help Message --}}
                            <small id="store_name_help" class="form-text text-muted">Please add store name</small>

                            {{-- Validation Failed --}}
                            <div id="invalid_store_name" class="invalid-feedback"></div>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

@section('footer_scripts')

    <script src="{{asset('/assets/vendor/select2/dist/js/select2.min.js')}}"></script>

    <script>

        /** Form variable */
        let form = $("#store_edit_form");

        /** Handle form submit on click */
        $('#form-submit').on('click', function (e){

            //Prevent form submission
            e.preventDefault();

            //Post form with AJAX
            postForm();
        });


        function postForm(){

            $.ajax({
                url: '{{route('stores.update',['store' => $store->id])}}',
                type:'patch',
                data:form.serialize(),
                beforeSend:function (){
                    $('.invalid-feedback').html('');
                },
                success:function(response){

                    if (response.errors){

                        /** Loop errors */
                        $.each(response.errors, function (errorIndex, error){

                            /** Add invalid class to input element */
                            $('#'+errorIndex).addClass('invalid');

                            /** Loop error messages */
                            $.each(error, function (messageIndex, error){
                                $('#invalid_'+errorIndex).addClass('show').append('<span class="error-message">'+error+'</span>')
                            });

                        })
                    } else if (response.url){
                        window.location=response.url;
                    }
                },
            });

        }

    </script>

@endsection

resources/views/layouts/stores/index.blade.php
@extends('layouts.app')

@push('extra-styles')

    <link href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" rel="stylesheet">

@endpush

@section('header')
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">{{trans('stores.stores_title')}}</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                @can('dashboard_view')
                                    <li class="breadcrumb-item"><a href="{{ route('home') }}"><i class="fas fa-home"></i></a></li>
                                @endcan
                                @can('stores-index')
                                    <li class="breadcrumb-item"><a href="{{ route('stores.index') }}">{{trans('stores.stores_title')}}</a></li>
                                @endcan
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">
                        @can('stores-index')
                            <a href="{{ route('stores.index') }}" class="btn btn-sm btn-neutral">Back</a>
                        @endcan
                        @can('stores-create')
                            <a href="{{route('stores.create')}}" class="btn btn-sm btn-neutral">{{ trans('stores.create_btn') }}</a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card card-frame">
                <div class="card-body">
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <div class="table-responsive">
                                    <div>
                                        <table id="table-stores" class="table align-items-center">
                                            <thead class="thead-light">
                                                <tr>
                                                    <th scope="col" class="sort" data-sort="id">ID</th>
                                                    <th scope="col" class="sort" data-sort="name">Name</th>
                                                    <th scope="col" class="sort" data-sort="name">Products</th>
                                                    <th scope="col"></th>
                                                </tr>
                                            </thead>
                                            <tbody class="list">

                                            @foreach($data->stores as $store)

                                                <tr>
                                                    <th scope="row">
                                                        @if(isset($store->id)){{$store->id}}@endif
                                                    </th>

                                                    <td class="name">
                                                        @if(isset($store->name)){{$store->name}}@endif
                                                    </td>

                                                    <td class="name">
                                                        @if(isset($store->products)){{$store->products->count()}}@endif
                                                    </td>

                                                    <td class="text-right">
                                                        <div class="dropdown">
                                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                                <i class="fas fa-ellipsis-v"></i>
                                                            </a>
                                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                                <a class="dropdown-item" href="{{ route('stores.show',['store' => $store->id]) }}">View</a>
                                                                <a class="dropdown-item" href="{{ route('stores.edit',['store' => $store->id]) }}">Edit</a>
                                                            </div>
                                                        </div>
                                                    </td>

                                                </tr>

                                            @endforeach

                                            </tbody>
                                        </table>
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('extra-scripts')

    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>

    <script>

        $(document).ready( function () {
            $('#table-stores').DataTable();
        } );
    </script>

@endpush

resources/views/layouts/stores/show.blade.php
@extends('layouts.app')

@section('header')

    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">{{trans('stores.stores_title')}}</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                @can('dashboard_view')
                                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="fas fa-home"></i></a></li>
                                @endcan
                                @can('stores-index')
                                    <li class="breadcrumb-item"><a href="{{ route('stores.index') }}">{{trans('stores.stores_title')}}</a></li>
                                @endcan
                                @can('stores-create')
                                    <li class="breadcrumb-item active" aria-current="page">{{trans('stores.view')}}</li>
                                @endcan
                            </ol>
                        </nav>
                    </div>
                    <div class="col-lg-6 col-5 text-right">
                        @can('stores-index')
                            <a href="{{ route('stores.index') }}" class="btn btn-sm btn-neutral">Back</a>
                        @endcan
                        @can('stores-create')
                                <a href="{{ route('stores.edit',['store' => $data->id]) }}" class="btn btn-sm btn-neutral">Edit</a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')

    <div class="card mb-4">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    @if(isset($data->name))
                        <div class="form-group">
                            <label class="form-control-label">Product Name: </label>
                            <span class="d-block">{!! $data->name !!}</span>
                        </div>
                    @endif
                    @if(isset($data->price))
                        <div class="form-group">
                            <label class="form-control-label">Product Price: </label>
                            <span class="d-block">&euro;{!! number_format($data->price, 2) !!}</span>
                        </div>
                    @endif
                    @if(isset($data->category))
                        <div class="form-group">
                            <label class="form-control-label">Category Name: </label>
                            <span class="d-block">{!! $data->category->name !!}</span>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

@endsection